sudo: required
services:
  - docker 

before_install:
  - docker build -t peterjwhiting/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true peterjwhiting/react-test npm run test

after_success:
  - docker build -t peterjwhiting/multi-client ./client
  - docker build -t peterjwhiting/multi-nginx ./nginx
  - docker build -t peterjwhiting/multi-server ./server
  - docker build -t peterjwhiting/multi-worker ./worker
  # Login to Docker Home
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Push images to docker hub
  - docker push peterjwhiting/multi-client
  - docker push peterjwhiting/multi-nginx
  - docker push peterjwhiting/multi-server
  - docker push peterjwhiting/multi-worker